name: publish
on:
  push:
    branches:
      - develop
jobs:
  build-and-publish:
    runs-on: macos-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Cache cabal deps
        uses: actions/cache
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/fallible.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-
            ${{ runner.os }}-
      - name: Setup Haskell environment
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.4'
          enable-stack: true
      - name: Clean before building site
        run: cabal new-run site clean
      - name: Build site
        run: cabal new-run site build
      - name: Switch to master branch for publishing
        run: git checkout master
      - name: Synchronize pages
        run: chmod u+x sync.sh && ./sync.sh
